---
# tasks file for ansible-apf-firewall
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config_apf.yml
  when: config_apf_firewall

- include: config_bfd.yml
  when: config_apf_firewall_bfd
